"""
Train Models with Pipeline V3 - Clean Script

Treina modelos V17 (Totals) e V7 (Ensemble) usando feature_pipeline_v3
para garantir compatibility perfeita entre treino e validação.
"""

import pandas as pd
import numpy as np
from xgboost import XGBRegressor, XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score, accuracy_score, log_loss
import joblib
import logging
from pathlib import Path

from ml_pipeline.data_preparation import load_historical_data
from ml_pipeline.feature_pipeline_v3 import prepare_features_v3
from data.repositories.db_manager import get_db_manager

logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')
logger = logging.getLogger(__name__)


def train_totals_v17():
    """Train Totals Model V17 using Pipeline V3."""
    logger.info("=" * 70)
    logger.info("🏀 TRAINING TOTALS MODEL V17 (with Pipeline V3)")
    logger.info("=" * 70)
    
    # 1. Load data
    logger.info("📊 Loading historical data (RAW)...")
    df = load_historical_data(raw=True)
    logger.info(f"✅ Loaded {len(df)} games")
    
    # 2. Feature engineering with V3
    logger.info("🔧 Running Feature Pipeline V3...")
    df = prepare_features_v3(df)
    logger.info(f"✅ Features generated: {df.shape[1]} columns")
    
    # 3. Define target
    if 'total_points' not in df.columns:
        if 'home_score' in df.columns and 'away_score' in df.columns:
            df['total_points'] = df['home_score'] + df['away_score']
        else:
            logger.error("❌ Cannot find score columns")
            return
    
    # 4. Select features (use all generated by pipeline)
    valid_prefixes = [
        'home_rolling_', 'away_rolling_',
        'expected_', 'pace_',
        'home_rest_', 'away_rest_',
        'home_b2b', 'away_b2b',
        'home_games_', 'away_games_',
        'day_', 'month', 'is_weekend', 'season_',
        'home_rapm_', 'away_rapm_',
        'home_bpm_', 'away_bpm_',
        'rapm_', 'bpm_', 'depth_',
        'h2h_'
    ]
    feature_cols = [c for c in df.columns if any(c.startswith(p) for p in valid_prefixes) and df[c].dtype in ['int64', 'float64']]
    
    # Exclude features with ZERO importance (from feature_analysis_v3.py)
    exclude_zero_imp = [
        'home_rolling_30_pace', 'home_rolling_30_pie', 'home_rolling_30_off_rating', 
        'home_rolling_10_pace_y', 'home_rolling_10_def_rating', 'home_rolling_30_def_rating', 
        'home_rolling_10_win', 'home_rolling_10_off_rating', 'home_rolling_5_win', 
        'home_rolling_5_pace_y', 'home_rolling_5_off_rating', 'home_rolling_5_def_rating', 
        'home_rolling_5_pie', 'home_rolling_10_pie', 'away_rolling_5_def_rating', 
        'away_rolling_30_pace', 'away_rolling_30_def_rating', 'away_rolling_30_off_rating', 
        'away_rolling_10_ft_rate', 'away_rolling_10_def_rating', 'away_rolling_10_pace_y', 
        'away_rolling_10_pie', 'away_rolling_10_win', 'away_rolling_10_off_rating', 
        'away_rolling_5_pace_y', 'away_rolling_5_off_rating', 'home_rolling_30_win', 
        'away_rolling_5_pie', 'away_rolling_5_win', 'away_rolling_30_win', 
        'away_rolling_30_pie', 'home_rolling_30_pts', 'away_rolling_30_pts'
    ]
    feature_cols = [c for c in feature_cols if c not in exclude_zero_imp]
    
    logger.info(f"🎯 Using {len(feature_cols)} features")
    
    # 5. Clean data
    df_clean = df[feature_cols + ['total_points']].dropna()
    logger.info(f"✅ Clean dataset: {len(df_clean)} games")
    
    X = df_clean[feature_cols]
    y = df_clean['total_points']
    
    # 6. Train/test split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )
    
    # 7. Train model
    logger.info("🤖 Training XGBoost Regressor (Optimized)...")
    
    # Load best params
    try:
        best_params = joblib.load('data/models/best_params_v3.joblib')
        totals_params = best_params.get('totals_v17', {})
        logger.info(f"🔹 Using optimized params: {totals_params}")
    except Exception as e:
        logger.warning(f"⚠️ Could not load optimized params: {e}")
        totals_params = {
            'n_estimators': 500,
            'learning_rate': 0.05,
            'max_depth': 6,
            'objective': 'reg:absoluteerror',
            'n_jobs': -1,
            'random_state': 42
        }

    model = XGBRegressor(**totals_params)
    model.fit(X_train, y_train)
    
    # 8. Evaluate
    y_pred = model.predict(X_test)
    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    
    logger.info("=" * 70)
    logger.info("📊 TOTALS V17 RESULTS")
    logger.info("=" * 70)
    logger.info(f"MAE: {mae:.2f} points")
    logger.info(f"R²:  {r2:.4f}")
    logger.info("=" * 70)
    
    # 9. Feature importance
    importance = pd.DataFrame({
        'feature': feature_cols,
        'importance': model.feature_importances_
    }).sort_values('importance', ascending=False)
    
    logger.info("🏆 Top 10 Features:")
    for idx, row in importance.head(10).iterrows():
        logger.info(f"   {row['feature']:<30} {row['importance']:.4f}")
    
    # 10. Save model
    output_dir = Path('data/models')
    output_dir.mkdir(exist_ok=True, parents=True)
    
    model_path = output_dir / 'totals_model_v17.joblib'
    features_path = output_dir / 'totals_feature_names_v17.joblib'
    
    joblib.dump(model, model_path)
    joblib.dump(feature_cols, features_path)
    
    logger.info(f"\n💾 Model saved: {model_path}")
    logger.info(f"💾 Features saved: {features_path}")
    
    return model, mae, r2, feature_cols


def train_ensemble_v7():
    """Train Ensemble Model V7 using Pipeline V3."""
    logger.info("=" * 70)
    logger.info("🎯 TRAINING ENSEMBLE MODEL V7 (with Pipeline V3)")
    logger.info("=" * 70)
    
    # 1. Load data
    logger.info("📊 Loading historical data (RAW)...")
    df = load_historical_data(raw=True)
    logger.info(f"✅ Loaded {len(df)} games")
    
    # 2. Feature engineering with V3
    logger.info("🔧 Running Feature Pipeline V3...")
    df = prepare_features_v3(df)
    logger.info(f"✅ Features generated: {df.shape[1]} columns")
    
    # 3. Define target (home team won?)
    if 'winner' not in df.columns:
        if 'home_score' in df.columns and 'away_score' in df.columns:
            df['winner'] = (df['home_score'] > df['away_score']).astype(int)
        else:
            logger.error("❌ Cannot find score columns")
            return
    
    # 4. Select features
    valid_prefixes = [
        'home_rolling_', 'away_rolling_',
        'expected_', 'pace_',
        'home_rest_', 'away_rest_',
        'home_b2b', 'away_b2b',
        'home_games_', 'away_games_',
        'day_', 'month', 'is_weekend', 'season_',
        'home_rapm_', 'away_rapm_',
        'home_bpm_', 'away_bpm_',
        'rapm_', 'bpm_', 'depth_',
        'h2h_'
    ]
    feature_cols = [c for c in df.columns if any(c.startswith(p) for p in valid_prefixes) and df[c].dtype in ['int64', 'float64']]
    
    # Exclude features with ZERO importance (from feature_analysis_v3.py)
    exclude_zero_imp = [
        'home_rolling_5_efg_pct', 'home_rolling_5_ts_pct', 'home_rolling_5_tov_pct', 
        'home_rolling_30_pie', 'home_rolling_30_pace', 'home_rolling_30_def_rating', 
        'home_rolling_30_off_rating', 'home_rolling_30_ft_rate', 'home_rolling_30_oreb_pct', 
        'home_rolling_30_tov_pct', 'home_rolling_30_ts_pct', 'home_rolling_30_efg_pct', 
        'home_rolling_10_win', 'home_rolling_10_pts', 'home_rolling_10_pie', 
        'home_rolling_10_pace_y', 'home_rolling_10_def_rating', 'home_rolling_10_off_rating', 
        'home_rolling_10_ft_rate', 'home_rolling_10_oreb_pct', 'home_rolling_10_tov_pct', 
        'home_rolling_10_ts_pct', 'home_rolling_10_efg_pct', 'home_rolling_5_win', 
        'home_rolling_5_pts', 'home_rolling_5_pie', 'home_rolling_5_pace_y', 
        'home_rolling_5_def_rating', 'home_rolling_5_off_rating', 'home_rolling_5_ft_rate', 
        'home_rolling_5_oreb_pct', 'home_rolling_30_pts', 'home_rolling_30_win', 
        'away_rolling_5_efg_pct', 'away_rolling_5_ts_pct', 'away_rolling_30_pace', 
        'away_rolling_30_def_rating', 'away_rolling_30_off_rating', 'away_rolling_30_ft_rate', 
        'away_rolling_30_oreb_pct', 'away_rolling_30_tov_pct', 'away_rolling_30_ts_pct', 
        'away_rolling_30_efg_pct', 'away_rolling_10_win', 'away_rolling_10_pts', 
        'away_rolling_10_pie', 'away_rolling_10_pace_y', 'away_rolling_10_def_rating', 
        'away_rolling_10_off_rating', 'away_rolling_10_ft_rate', 'away_rolling_10_oreb_pct', 
        'away_rolling_10_tov_pct', 'away_rolling_10_ts_pct', 'away_rolling_10_efg_pct', 
        'away_rolling_5_win', 'away_rolling_5_pts', 'away_rolling_5_pie', 
        'away_rolling_5_pace_y', 'away_rolling_5_def_rating', 'away_rolling_5_off_rating', 
        'away_rolling_5_ft_rate', 'away_rolling_5_oreb_pct', 'away_rolling_5_tov_pct', 
        'away_games_in_7d', 'away_rolling_30_win', 'away_rolling_30_pie', 'away_rolling_30_pts'
    ]
    feature_cols = [c for c in feature_cols if c not in exclude_zero_imp]
    
    logger.info(f"🎯 Using {len(feature_cols)} features")
    
    # 5. Clean data
    df_clean = df[feature_cols + ['winner']].dropna()
    logger.info(f"✅ Clean dataset: {len(df_clean)} games")
    
    X = df_clean[feature_cols]
    y = df_clean['winner']
    
    # Ensure winner is 0/1
    if y.dtype == 'object':
        y = (y == 'HOME').astype(int)
    
    # 6. Train/test split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )
    
    # 7. Train model
    logger.info("🤖 Training XGBoost Classifier (Optimized)...")
    
    # Load best params
    try:
        best_params = joblib.load('data/models/best_params_v3.joblib')
        ensemble_params = best_params.get('ensemble_v7', {})
        logger.info(f"🔹 Using optimized params: {ensemble_params}")
    except Exception as e:
        logger.warning(f"⚠️ Could not load optimized params: {e}")
        ensemble_params = {
            'n_estimators': 500,
            'learning_rate': 0.05,
            'max_depth': 6,
            'objective': 'binary:logistic',
            'eval_metric': 'logloss',
            'n_jobs': -1,
            'random_state': 42
        }
        
    model = XGBClassifier(**ensemble_params)
    model.fit(X_train, y_train)
    
    # 8. Evaluate
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:, 1]
    
    accuracy = accuracy_score(y_test, y_pred)
    logloss = log_loss(y_test, y_prob)
    
    logger.info("=" * 70)
    logger.info("📊 ENSEMBLE V7 RESULTS")
    logger.info("=" * 70)
    logger.info(f"Accuracy: {accuracy:.4f} ({accuracy*100:.2f}%)")
    logger.info(f"Log Loss: {logloss:.4f}")
    logger.info("=" * 70)
    
    # 9. Save model
    output_dir = Path('data/models')
    output_dir.mkdir(exist_ok=True, parents=True)
    
    model_path = output_dir / 'ensemble_model_v7.joblib'
    features_path = output_dir / 'ensemble_feature_names_v7.joblib'
    
    joblib.dump(model, model_path)
    joblib.dump(feature_cols, features_path)
    
    logger.info(f"\n💾 Model saved: {model_path}")
    logger.info(f"💾 Features saved: {features_path}")
    
    return model, accuracy, logloss, feature_cols


if __name__ == "__main__":
    logger.info("\n🚀 Starting training with Pipeline V3\n")
    
    # Train Totals V17
    logger.info("\n" + "="*70)
    logger.info("PART 1: TOTALS MODEL V17")
    logger.info("="*70 + "\n")
    
    totals_model, totals_mae, totals_r2, totals_features = train_totals_v17()
    
    # Train Ensemble V7
    logger.info("\n\n" + "="*70)
    logger.info("PART 2: ENSEMBLE MODEL V7")
    logger.info("="*70 + "\n")
    
    ensemble_model, ensemble_acc, ensemble_logloss, ensemble_features = train_ensemble_v7()
    
    # Summary
    logger.info("\n\n" + "="*70)
    logger.info("🎉 TRAINING COMPLETE")
    logger.info("="*70)
    logger.info(f"\nTotals V17:")
    logger.info(f"  - MAE: {totals_mae:.2f} points")
    logger.info(f"  - R²: {totals_r2:.4f}")
    logger.info(f"  - Features: {len(totals_features)}")
    logger.info(f"\nEnsemble V7:")
    logger.info(f"  - Accuracy: {ensemble_acc*100:.2f}%")
    logger.info(f"  - Log Loss: {ensemble_logloss:.4f}")
    logger.info(f"  - Features: {len(ensemble_features)}")
    logger.info("\n✅ Models ready for validation!")
    logger.info("="*70 + "\n")
